var express = require('express');
var router = express.Router();
var supabaseAdmin = require('../config/supabaseAdmin');
var { requireAuth } = require('../middleware/auth');
var PDFDocument = require('pdfkit');

/* ---------- Create a journal entry ---------- */
router.post('/', requireAuth, async function (req, res) {
  var { decisionId, content } = req.body;

  var { data, error } = await supabaseAdmin
    .from('journals')
    .insert({
      user_id: req.user.id,
      decision_id: decisionId,
      content: content
    })
    .select()
    .single();

  if (error) return res.status(500).json({ error: error.message });
  res.json({ journal: data });
});

/* ---------- Get all journals for logged-in user ---------- */
/* ---------- SCRUM-140: Journal History Query and Sorting ---------- */
router.get('/', requireAuth, async function (req, res) {
  var { sortBy, order, decisionId } = req.query;

  var validSortFields = ['created_at', 'updated_at'];
  var validOrders = ['asc', 'desc'];

  var sortField = validSortFields.includes(sortBy) ? sortBy : 'created_at';
  var sortOrder = validOrders.includes(order) ? order === 'asc' : false;

  var query = supabaseAdmin
    .from('journals')
    .select('*')
    .eq('user_id', req.user.id)
    .order(sortField, { ascending: sortOrder });

  if (decisionId) query = query.eq('decision_id', decisionId);

  var { data, error } = await query;

  if (error) return res.status(500).json({ error: error.message });
  res.json({ journals: data });
});

/* ---------- SCRUM-132 + 135: Generate and Return Journal PDF ---------- */
router.get('/:id/pdf', requireAuth, async function (req, res) {

  var { data: journal, error: journalError } = await supabaseAdmin
    .from('journals')
    .select('*, decisions(title, category, decision_text, regret_rating)')
    .eq('id', req.params.id)
    .eq('user_id', req.user.id)
    .single();

  if (journalError || !journal) {
    return res.status(404).json({ error: 'Journal not found' });
  }

  var { data: user } = await supabaseAdmin
    .from('users')
    .select('first_name, last_name')
    .eq('id', req.user.id)
    .single();

  var fullName = user ? user.first_name + ' ' + user.last_name : 'Unknown';
  var decision = journal.decisions || {};
  var createdAt = new Date(journal.created_at).toDateString();

  var doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    'attachment; filename="journal-' + req.params.id + '.pdf"'
  );

  doc.pipe(res);

  doc.fontSize(24).font('Helvetica-Bold').text('DeathBed — Pre-Mortem Journal', { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).font('Helvetica').text('Author: ' + fullName);
  doc.text('Date: ' + createdAt);

  doc.moveDown();
  doc.fontSize(16).font('Helvetica-Bold').text('Decision');
  doc.moveDown(0.5);
  doc.fontSize(12).font('Helvetica');
  doc.text('Title: ' + (decision.title || 'N/A'));
  doc.text('Category: ' + (decision.category || 'N/A'));
  doc.moveDown(0.5);
  doc.text(decision.decision_text || 'No decision text provided.');

  if (decision.regret_rating) {
    doc.moveDown();
    doc.fontSize(16).font('Helvetica-Bold').text('Regret Rating');
    doc.fontSize(12).font('Helvetica').text(decision.regret_rating + ' / 10');
  }

  doc.moveDown();
  doc.fontSize(16).font('Helvetica-Bold').text('Journal Entry');
  doc.moveDown(0.5);
  doc.fontSize(12).font('Helvetica').text(journal.content || 'No content.');

  doc.moveDown(2);
  doc.fontSize(10).fillColor('grey').text('Generated by DeathBed — Regret Prevention Engine', { align: 'center' });

  doc.end();
});

module.exports = router;